### ISSUE TITLE
Type widened

### ISSUE THREAD

**Issue by Jack-Works** [Austaras/playground#1]
Type widened in https://github.com/Austaras/playground/blob/master/typescript-tricks/validate/index.ts#L13

When declaring `rules`, type `Record<string, Function | null>` is assigned. Then the accurate type lost.

Consider

```ts
function validateRules<T extends Record<string, Function | null>>(x: T) {}
const rules = {
    '': null,
    hex(val: string) {
        return val.match(/^(0x|0X)?[a-fA-F\d]+$/) ? true : false
    },
    moreThan20(val: number) {
        return val > 20
    }
}
validateRules(rules)
```

Then `type rule = keyof typeof rules` evaluates to `type rule = "" | "hex" | "moreThan20"`

**Comment by Austaras** [comment]
well I did write this in a hurry
